name: 'Create Cluster'
description: 'Create Cluster'
inputs:
  replicated-api-token:
    description: 'Replicated API Token.'
    required: true
    default: ''
  kubernetes-distribution:
    description: 'Kubernetes distribution of the cluster to provision (default "kind")'
    required: true
    default: 'kind'
  kubernetes-version:
    description: 'Kubernetes version to provision (format is distribution dependent) (default "v1.25.3")'
    required: true
    default: 'v1.25.3'
  cluster-name:
    description: 'Name of the cluster to provision'
    required: true
    default: ''
  ttl:
    description: 'Cluster TTL (duration) (default "1h")'
    required: true
    default: '1h'
outputs:
  cluster-id: # id of the cluster
    description: 'Contains the cluster id.'
  cluster-status: # status of the cluster
    description: 'Contains the cluster status.'
  cluster-kubeconfig: # kubeconfig of the cluster
    description: 'Contains the kubeconfig to connect with the cluster.'
runs:
  using: 'node16'
  main: 'dist/index.js'