name: 'Replicated create release'
description: 'Create a Replicated release on a channel'
inputs:
  replicated-app:
    description: 'Replicated App Slug.'
    required: true
    default: ''
  replicated-api-token:
    description: 'Replicated API Token.'
    required: true
    default: ''
  yaml-dir:
    description: 'The directory containing multiple yamls for a Replicated release.'
    required: true
    default: 'manifests'
  promote-channel:
    description: 'Channel name or id to promote this release to.'
    required: true
    default: '${GITHUB_REF}'
  version:
    description: 'Release version'
    required: true
    default: '${GITHUB_SHA::7}'
outputs:
  release-sequence: # sequence number of the release
    description: 'Sequence number of the release.'
    value: ${{ steps.inspect-channel.outputs.release-sequence }}
runs:
  using: "composite"
  steps:
  - name: 'Create the release'
    id: 'cli-create-release'
    uses: replicatedhq/reliability-actions-lib/create-release@v0.0.1-alpha.5
    with:
      replicated-app: ${{ inputs.replicated-app }}
      replicated-api-token: ${{ inputs.replicated-api-token }}
      yaml-dir: ${{ inputs.yaml-dir }}
      version: ${{ inputs.version }}
      promote-channel: ${{ inputs.promote-channel }}
  - name: 'Inspect a channel'
    id: 'inspect-channel'
    uses: replicatedhq/reliability-actions-lib/inspect-channel@v0.0.1-alpha.5
    with:
      replicated-app: ${{ inputs.replicated-app }}
      replicated-api-token: ${{ inputs.replicated-api-token }}
      channel-name: ${{ inputs.promote-channel }}