name: 'Archive Customer'
description: 'Archive a customer'
inputs:
  app-slug:
    description: 'App Slug.'
    required: true
    default: ''
  api-token:
    description: 'API Token.'
    required: true
    default: ''
  customer-id:
    description: 'The id of the customer.'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'