name: 'Archive Channel'
description: 'Archive a channel'
inputs:
  app-slug:
    description: 'App Slug.'
    required: true
    default: ''
  api-token:
    description: 'API Token.'
    required: true
    default: ''
  channel-slug:
    description: 'The slug of the channel to archive.'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'